# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.out_label = QtWidgets.QLabel(self.centralwidget)
        self.out_label.setGeometry(QtCore.QRect(10, 10, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.out_label.setFont(font)
        self.out_label.setFrameShape(QtWidgets.QFrame.Box)
        self.out_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.out_label.setObjectName("out_label")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("2"))
        self.button_2.setGeometry(QtCore.QRect(100, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("1"))
        self.button_1.setGeometry(QtCore.QRect(10, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("3"))
        self.button_3.setGeometry(QtCore.QRect(190, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("+"))
        self.button_plus.setGeometry(QtCore.QRect(280, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_plus.setFont(font)
        self.button_plus.setObjectName("button_plus")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("4"))
        self.button_4.setGeometry(QtCore.QRect(10, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("5"))
        self.button_5.setGeometry(QtCore.QRect(100, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("-"))
        self.button_minus.setGeometry(QtCore.QRect(280, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("6"))
        self.button_6.setGeometry(QtCore.QRect(190, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("7"))
        self.button_7.setGeometry(QtCore.QRect(10, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("8"))
        self.button_8.setGeometry(QtCore.QRect(100, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_mult = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("*"))
        self.button_mult.setGeometry(QtCore.QRect(280, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_mult.setFont(font)
        self.button_mult.setObjectName("button_mult")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("9"))
        self.button_9.setGeometry(QtCore.QRect(190, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_percent = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("%"))
        self.button_percent.setGeometry(QtCore.QRect(10, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_percent.setFont(font)
        self.button_percent.setObjectName("button_percent")
        self.button_c = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("C"))
        self.button_c.setGeometry(QtCore.QRect(100, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_c.setFont(font)
        self.button_c.setObjectName("button_c")
        self.button_divide = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("/"))
        self.button_divide.setGeometry(QtCore.QRect(280, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        self.button_arrow = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.remove())
        self.button_arrow.setGeometry(QtCore.QRect(190, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_arrow.setFont(font)
        self.button_arrow.setObjectName("button_arrow")
        self.button_plusminus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus())
        self.button_plusminus.setGeometry(QtCore.QRect(10, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_plusminus.setFont(font)
        self.button_plusminus.setObjectName("button_plusminus")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("0"))
        self.button_0.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.equal())
        self.button_equal.setGeometry(QtCore.QRect(280, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_equal.setFont(font)
        self.button_equal.setObjectName("button_equal")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot())
        self.button_dot.setGeometry(QtCore.QRect(190, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_dot.setFont(font)
        self.button_dot.setObjectName("button_dot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def plus_minus(self):
        screen = self.out_label.text()

        if screen[0] == "-":
            self.out_label.setText(screen[1::])
        else:
            self.out_label.setText(f'-{screen}')

    # Function to evaluate the result:
    def equal(self):
        screen = self.out_label.text()
        try:
            result = eval(screen)
            self.out_label.setText(str(result))
        except:
            self.out_label.setText("Error")

    # Function to delete the last character:
    def remove(self):
        screen = self.out_label.text()
        screen = screen[:-1]
        self.out_label.setText(f'{screen}')

    # Function for the dot button:
    def dot(self):
        screen = self.out_label.text()
        list = ["+", "-", "*", "/"]
        is_valid = True
        for i in screen:
            if i in list:
                is_valid = True
            elif i == ".":
                is_valid = False
        if is_valid:
            self.out_label.setText(f'{screen}.')

    # function for pressing the button functionality:
    def pressed(self, button):
        if button == "C":
            self.out_label.setText("0")
        else:
            if self.out_label.text() == "0":
                self.out_label.setText("")
            self.out_label.setText(f'{self.out_label.text()}{button}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.out_label.setText(_translate("MainWindow", "0"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_mult.setText(_translate("MainWindow", "*"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_percent.setText(_translate("MainWindow", "%"))
        self.button_c.setText(_translate("MainWindow", "C"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_arrow.setText(_translate("MainWindow", "<<"))
        self.button_plusminus.setText(_translate("MainWindow", "+/-"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_dot.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
